/**
 * Typed asset keys — single source of truth for every string used to load or
 * reference an asset. Keeps the codebase free of magic strings and makes it
 * obvious what exists. Populated as milestones add assets.
 */
export const SceneKeys = {
  Boot: "BootScene",
  Preload: "PreloadScene",
  Menu: "MenuScene",
  Game: "GameScene",
  UI: "UIScene",
  Pause: "PauseScene",
  LevelComplete: "LevelCompleteScene",
  GameOver: "GameOverScene",
} as const;

export type SceneKey = (typeof SceneKeys)[keyof typeof SceneKeys];

/**
 * Texture keys for procedurally generated art (TextureFactory) and, later,
 * any loaded image assets. To swap in your own art, register an image under
 * the same key in PreloadScene instead of generating it — nothing else changes.
 */
export const TextureKeys = {
  Tiles: "tex_tiles", // terrain tileset (grid of 32px tiles)
  Sky: "tex_sky", // parallax: static gradient sky
  HillsFar: "tex_hills_far", // parallax: distant hills (tiled)
  HillsNear: "tex_hills_near", // parallax: closer hills (tiled)
  Beacon: "tex_beacon", // level-end goal marker
  // Interactive entities (standalone sprite textures)
  LuckyBlock: "tex_lucky", // "?" block (active)
  Brick: "tex_brick", // breakable brick
  UsedBlock: "tex_used", // spent "?" block
  Coin: "tex_coin", // collectible coin
  Growcap: "tex_growcap", // grow power-up
  // Enemies & obstacles
  Plodder: "tex_plodder", // walking enemy
  Snapvine: "tex_snapvine", // piranha-style plant
  Pipe: "tex_pipe", // pipe obstacle / plant housing
  // Particle bits
  Spark: "tex_spark", // coin/sparkle particle
  Crumb: "tex_crumb", // brick-fragment particle
  Puff: "tex_puff", // stomp/dust particle
} as const;

/**
 * Player character art — frame texture keys and animation keys for both sizes.
 * Frames are generated by TextureFactory; animations are registered in
 * PreloadScene. Centralized so Player, the factory and the loader agree.
 */
export const PlayerArt = {
  tex: {
    small: {
      idle: "lumio_s_idle",
      run0: "lumio_s_run0",
      run1: "lumio_s_run1",
      run2: "lumio_s_run2",
      run3: "lumio_s_run3",
      jump: "lumio_s_jump",
    },
    big: {
      idle: "lumio_b_idle",
      run0: "lumio_b_run0",
      run1: "lumio_b_run1",
      run2: "lumio_b_run2",
      run3: "lumio_b_run3",
      jump: "lumio_b_jump",
    },
  },
  anim: {
    small: { idle: "lumio-s-idle", run: "lumio-s-run", jump: "lumio-s-jump" },
    big: { idle: "lumio-b-idle", run: "lumio-b-run", jump: "lumio-b-jump" },
  },
} as const;

